### ISSUE TITLE
make fails with "error: will never be executed"

### ISSUE THREAD

**Issue by 9uuso** [mist64/xhyve#1]
Hi, I tried following the instructions on your blog post, but ran into an error:

```
08:43:20 ~/Github/xhyve $ make
cc src/vmm/io/vrtc.c
src/vmm/io/vrtc.c:168:30: error: will never be executed [-Werror,-Wunreachable-code]
            (sizeof(time_t) == 4 && year > 2037)) {     /* time_t overflow */
                                    ^~~~
1 error generated.
make: *** [build/vmm/io/vrtc.o] Error 1
```

If you need any more information, please let me know. An interesting project you have here, nonetheless.

**Comment by mist64** [comment]
Which version of OS X and clang are you using?

**Comment by 9uuso** [comment]
OSX version is 10.10.3 on late-2013 MBPr.

Clang:
```
Apple LLVM version 5.1 (clang-503.0.38) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

Anyhow, I removed the `-Weverything` flag from [config.mk](https://github.com/mist64/xhyve/blob/master/config.mk#L35) and it compiled successfully.

**Comment by mist64** [comment]
Can you test whether reversing the && fixes the warning?

    (year > 2037 && sizeof(time_t) == 4)

I'd commit this change then.

**Comment by 9uuso** [comment]
:+1: The change fixes the compiling issue.
