### ISSUE TITLE
vmx_init: processor does not support desired exit controls

### ISSUE THREAD

**Issue by dacort** [mist64/xhyve#10]
Similar to #3, I have a fairly recent MacBook Air:
> Model Name:	MacBook Air
> Model Identifier:	MacBookAir6,1
> Processor Name:	Intel Core i7
> Processor Speed:	1.7 GHz
> Number of Processors:	1
> Total Number of Cores:	2
> L2 Cache (per Core):	256 KB
> L3 Cache:	4 MB
> Memory:	8 GB
> Boot ROM Version:	MBA61.0099.B18
> SMC Version (system):	2.12f143

Running OS X 10.10.2

I receive the following error trying to run xhyve.sh after a successful make:
> vmx_init: processor does not support desired exit controls
> Unable to create VM (22)

**Comment by haldean** [comment]
I get the same error, with a 2014 MacBook Pro. My specs:

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP112.0138.B11
  SMC Version (system):	2.19f12
```

**Comment by mist64** [comment]
xhyve should print another warning line, like:

    vmx_set_ctlreg: cap_field: 2 bit: 16 unspecified don't care

Can you please paste it?

**Comment by dacort** [comment]
@mist64 Unfortunately only seeing the error I pasted above. No additional info.

**Comment by haldean** [comment]
Ditto

**Comment by dacort** [comment]
Also, I _just_ upgraded to 10.10.4 and now the VM launches fine. @haldean can you help debug further if necessary?

**Comment by haldean** [comment]
Sure; I'm still on 10.10.1 and I'm not planning on upgrading any time soon. @mist64, is there any debugging I could turn on for you to get you more info?

**Comment by ailispaw** [comment]
Same problem here with 10.10.2 at https://github.com/mist64/xhyve/blob/master/src/vmm/intel/vmx.c#L507-L515 .

Hypervisor Changes
https://developer.apple.com/library/mac/releasenotes/General/APIDiffsMacOSX10_10_3/frameworks/Hypervisor.html
> hv_vmx.h
> Added HV_VMX_CAP_EXIT
> Added HV_VMX_CAP_PREEMPTION_TIMER

It seems HV_VMX_CAP_EXIT added from 10.10.3.

**Comment by dacort** [comment]
@ailispaw Ah, that would totally make sense then why it worked fine after I upgraded.

**Comment by petiepooo** [comment]
That would also explain why I get this error on 10.9.5:
<pre>src/vmm/intel/vmx.c:507:25: error: use of undeclared identifier 'HV_VMX_CAP_EXIT'; did you mean 'HV_VMX_CAP_ENTRY'?
        error = vmx_set_ctlreg(HV_VMX_CAP_EXIT,
                               ^~~~~~~~~~~~~~~
                               HV_VMX_CAP_ENTRY
In file included from src/vmm/intel/vmx.c:37:
</pre>

**Comment by dacort** [comment]
@petiepooo Correct, see #4 and #7.

**Comment by mist64** [comment]
REAME now states you need 10.10.3, closing.
