### ISSUE TITLE
OSX guest?

### ISSUE THREAD

**Issue by eunikolsky** [mist64/xhyve#105]
Hi.
Is it possible to support OS X apps in xhyve?
As I understand, LXC in linux uses the running kernel for virtualization, so is it possible to do the same on OSX with `Hypervisor.framework`? Couldn't find any information about that. It'd probably require EFI support and some launcher like the one for `hvdos` (http://www.pagetable.com/?p=764).
Thanks.

**Comment by martinborgman** [comment]
If I understand correctly you would like to run an OS X app in a container like a docker container?
If that is the case, most OS X applications already run in a container. On OS X this is called the App Sandbox, see: [App Sandbox in Depth](https://developer.apple.com/library/mac/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html)
Xhyve is more like QEMU KVM.

**Comment by eunikolsky** [comment]
> If I understand correctly you would like to run an OS X app in a container like a docker container?

yes, I'm particularly interested in running multiple iOS simulators for tests.

I think app sandbox is different — it has to be supported by the app, but with xhyve/docker we could enforce isolation from the outside.

> Xhyve is more like QEMU KVM.

oh, I had to read about KVM vs LXC to understand this distinction better. so the issue is that the `Hypervisor.framework` is, like KVM, for full Virtual Machines? and there is no native containers support on OSX?

**Comment by 07151129** [comment]
>  so the issue is that the Hypervisor.framework is, like KVM, for full Virtual Machines?

Yes.

> and there is no native containers support on OSX?

No.

**Comment by eunikolsky** [comment]
thanks, @martinborgman and @07151129. have to wait for `Container.framework` then.

**Comment by cybertk** [comment]
There is no clue of **Container.framework** after a quick google, what's that?
