### ISSUE TITLE
Feature request - Support xhyve as vagrant driver

### ISSUE THREAD

**Issue by SydOps** [mist64/xhyve#110]
I am user of vagrant and native docker for mac, currently have issue to start vagrant with native docker, (https://github.com/mitchellh/vagrant/issues/7240), because there is no proper plug-in in vagrant. 

Native Docker engine is running in an Alpine Linux distribution on top of an xhyve Virtual Machine on Mac OS X 

Any chance to add a new feature to support or develop a new vagrant xhyve driver (plug-in) ? Then we can use it to start native docker image in vagrant directly.

**Comment by 0x414A** [comment]
Some existing efforts at making that happen:

https://github.com/sirn/vagrant-xhyve
https://github.com/oldpatricka/vagrant-xhyve

Though it looks like these projects are in their infancy.

**Comment by SydOps** [comment]
Thanks, @0x414A 

The function has been fixed by Vagrant directly with `d.force_host_vm = false`.  See my original ticket: 

https://github.com/mitchellh/vagrant/issues/7240
