### ISSUE TITLE
Why xhyve can run with VirtualBox at same time?

### ISSUE THREAD

**Issue by jjqq2013** [mist64/xhyve#136]
Hi, this is not a bug report.  
As i know, only one Hypervisor can be run at same time, 
why would xhyve and VirtualBox can run at same time?

Does it means VirtualBox does not install a Hypervisor on Mac OS X, instead, it just install an extension to existing Hypervisor?

**Comment by rickard-von-essen** [comment]
You _can_ run multiple hypervisors at the same time, I do that alot, as long as they are well behaving and clean up after themselves. There has been issues around this in the past with VirtualBox, but they have been fixed.

**Comment by jjqq2013** [comment]
@rickard-von-essen Thanks for the clear answer. I'v been thinking Hypervisors can not coexist because i have seen on Windows, VirtualBox can not run when Hyper-V running.
OK, closed.
