### ISSUE TITLE
sshd segfault on successful auth

### ISSUE THREAD

**Issue by proppy** [mist64/xhyve#2]
Not sure if that's a `xhyve` issue (or a boot2docker one), but I noticed that `sshd` was segfaulting on boot2docker when run inside xhyve, see below.

#### run boot2docker with xhyve
```
curl https://github.com/boot2docker/boot2docker/releases/download/v1.6.2/boot2docker.iso
hdiutil attach boot2docker.iso
mkdir boot2docker
cp /Volumes/Boot2Docker-v1.6/boot/{vmlinuz64,initrd.img} boot2docker/
build/xhyve -m 1G -s 0:0,hostbridge -s 31,lpc -l com1,stdio -s 2:0,virtio-net -s 3,ahci-cd,boot2docker/boot2docker.iso -f kexec,boot2docker/vmlinuz64,boot2docker/initrd.img,earlyprintk=serial console=ttyS0 acpi=off
```

#### ssh segfault
```
$ nmap -sP 192.168.64.1/24
$ ssh docker@192.168.64.x
sshd[675]: segfault at 0 ip 00000000f7514b84 sp 00000000ff8fa464 error 4 in libc-2.17.so[f74ad000+117000]
```

**Comment by xez** [comment]
You might want to append the boot2docker kernel boot-args from the isolinux.cfg on the iso. Works for me.

`user=docker noembed nomodeset norestore waitusb=10:LABEL=boot2docker-data base`

**Comment by proppy** [comment]
@xez worked fine, thanks!
