### ISSUE TITLE
CentOS 6.6: failed to load kernel

### ISSUE THREAD

**Issue by patu90da** [mist64/xhyve#21]
I've tried to install [this way](http://www.pagetable.com/?p=831) to reference, but I could not install.

Error Message:
```
kexec: failed to load kernel centos/vmlinuz
  ./xhyverun_centos_install.sh: line 15: 13387 Abort trap: 6           build/xhyve $MEM $SMP $PCI_DEV $LPC_DEV $NET $IMG_CD $IMG_HDD -f kexec,$KERNEL,$INITRD,"$CMDLINE"
```

Shell Script
```
#!/bin/sh

KERNEL="centos/vmlinuz"
INITRD="centos/initrd.img"
CMDLINE="earlyprintk=serial console=ttyS0 acpi=off"

MEM="-m 1G"
#SMP="-c 2"
NET="-s 2:0,virtio-net"
IMG_CD="-s 3,ahci-cd,centos/CentOS-6.6-x86_64-minimal.iso"
# IMG_HDD="-s 4,virtio-blk,centos/hdd.img"
PCI_DEV="-s 0:0,hostbridge -s 31,lpc"
LPC_DEV="-l com1,stdio"

build/xhyve $MEM $SMP $PCI_DEV $LPC_DEV $NET $IMG_CD $IMG_HDD -f kexec,$KERNEL,$INITRD,"$CMDLINE"
```

Environment
* Host: OS X Yosemite 10.10.3 on MacBook Air (Mid 2013)
* ISO: CentOS-6.6-x86_64-minimal.iso

**Comment by mist64** [comment]
Reproduced:

    $ file centos/vmlinuz 
    centos/vmlinuz: Linux kernel x86 boot executable bzImage, version 2.6.32-504.el6.x86_64 (mockbuil, RO-rootFS, swap_dev 0x3, Normal VGA
    $ md5 centos/vmlinuz 
    MD5 (centos/vmlinuz) = 0805f85b126ebc6adf84b6ead56a080b
    $ ./xhyverun-centos.sh 
    kexec: failed to load kernel centos/vmlinuz

**Comment by mist64** [comment]
You can get CentOS 6.6 working by commenting out this line in kexec.c:

    (zp->setup_header.version < 0x020c) ||    /* too old */

The vmlinuz in the ISO has a version of 0x20c, but it seems to work anyway. I'll have to look into what exactly the version means and whether we can be more forgiving.
