### ISSUE TITLE
assertion failure in src/pci_virtio_vmnet.c, line 476

### ISSUE THREAD

**Issue by danielnorberg** [mist64/xhyve#25]
Sporadically hit this using https://github.com/ailispaw/boot2docker-xhyve:

```
sudo ./xhyverun.sh
Assertion failed: (sc->vms), function pci_vtnet_tap_rx, file src/pci_virtio_vmnet.c, line 476.
./xhyverun.sh: line 17: 35451 Abort trap: 6           xhyve $MEM $SMP $PCI_DEV $LPC_DEV $NET $IMG_CD $IMG_HDD $UUID -f kexec,$KERNEL,$INITRD,"$CMDLINE"
```

**Comment by xez** [comment]
Ran into this as well. Hopefully fixed with https://github.com/mist64/xhyve/pull/26.

**Comment by mist64** [comment]
@danielnorberg Can you verify?

**Comment by ailispaw** [comment]
@danielnorberg @xez @mist64 
I have never had that error with boot2docker-xhyve after #26.
Thanks.
