### ISSUE TITLE
Please tag a version!

### ISSUE THREAD

**Issue by dguerri** [mist64/xhyve#27]
It would be great to have Xhyve in homebrew (see https://github.com/Homebrew/homebrew/pull/40812), but they prefer to have clearly defined versions.

Could you please tag a release?

**Comment by rimusz** [comment]
+1

**Comment by AntonioMeireles** [comment]
+1

**Comment by prefork** [comment]
I added this to head-only in the meantime.
https://github.com/Homebrew/homebrew-head-only/blob/master/xhyve.rb

**Comment by zchee** [comment]
@prefork Cool !

**Comment by dguerri** [comment]
:+1:

**Comment by mist64** [comment]
Tagged current master (which seems decently stable) as v0.1.0:
https://github.com/mist64/xhyve/releases/tag/v0.1.0

**Comment by blackgear** [comment]
I added v0.1.0 to homebrew mainline. The formula is pending this time.
See https://github.com/Homebrew/homebrew/pull/40936

**Comment by dguerri** [comment]
@mist64 you are awesome :) Thanks.
