### ISSUE TITLE
Cannot create VM(22)

### ISSUE THREAD

**Issue by hbp** [mist64/xhyve#3]
I have a very recent MacBook Air :

> Model Name:	MacBook Air
>  Model Identifier:	MacBookAir7,2
>  Processor Name:	Intel Core i5
>  Processor Speed:	1,6 GHz
>  Number of Processors:	1
>  Total Number of Cores:	2
>  L2 Cache (per Core):	256 KB
>  L3 Cache:	3 MB
>  Memory:	8 GB
>  Boot ROM Version:	MBA71.0166.B02
>  SMC Version (system):	2.27f1

Running

> System Version:	OS X 10.10.3 (14D136)
>   Kernel Version:	Darwin 14.3.0
>   Boot Volume:	Macintosh HD
>   Boot Mode:	Normal
>   Secure Virtual Memory:	Enabled

After a successful make, running xhyve.sh results in the following : 

> vmx_set_ctlreg: cap_field: 2 bit: 16 unspecified don't care
> vmx_init: processor does not support desired secondary processor-based controls
> Unable to create VM (22)

Error messages originate in src/vmm/intel/vmx.c

If I comment out the error call at line 489 and rebuild then tinycorelinux comes up.

**Comment by mist64** [comment]
Fixed in 7ffd07108710349c1480f7d176e2cc7f6629de3e
