### ISSUE TITLE
please tag a new version

### ISSUE THREAD

**Issue by AntonioMeireles** [mist64/xhyve#32]
@mist64 could you please tag a new version (to be consumed by homebrew et al.). In particular @xez bsd stuff that got merged last night is particularly handy as it *en passant* fixed a bunch of (acpi related) stuff that also affected linux guests....

**Comment by mist64** [comment]
I'd like to wait a bit and see whether bug reports come in.

**Comment by AntonioMeireles** [comment]
ok, thnxs - fair point. (fwiw, i've been running that one, and a few other hand picked patches, for a few days without any major issues ([here](https://github.com/AntonioMeireles/xhyve/commits/edgy) is what has been catching my eye) so far)

**Comment by AntonioMeireles** [comment]
@mist64 *please*... (the acpi fixes and the tap stuff would be very handy elsewhere... and afaict there are no reports of breakage due to those). **THANKS**!

**Comment by jeantil** [comment]
a new version tag would indeed be nice

**Comment by bartekrutkowski** [comment]
@mist64 New tag would allow us to release the new code to Homebrew package and enable even more users to use it, what in turn should generate more bug reports, than less ;) I think people that are going to play with it are aware this is a work in progress software, so there's very little harm in tagging more often!

**Comment by mist64** [comment]
v0.2.0 has been released. :)

**Comment by rimusz** [comment]
nice
