### ISSUE TITLE
RAM limited to 3GB

### ISSUE THREAD

**Issue by jakajancar** [mist64/xhyve#37]
At least with the bundled image, again. Not sure if this is expected or not.

**Comment by xez** [comment]
The setup of the memory map in `src/firmware/kexec.c` currently only takes into account memory below 3 GB, should be an easy fix.

**Comment by nlf** [comment]
any movement towards fixing this?

**Comment by nlf** [comment]
@xez any hints on how to implement this? my C is a bit rusty, but if you can point me in the right direction i can probably figure it out

**Comment by mist64** [comment]
Fixed in 793d17ccffa9a1f74f6f1a4997e73cb2e1496296
