### ISSUE TITLE
Build error with `HV_VMX_CAP_EXIT`

### ISSUE THREAD

**Issue by rjp** [mist64/xhyve#4]
cc src/vmm/intel/vmx.c
    src/vmm/intel/vmx.c:507:25: error: use of undeclared identifier 'HV_VMX_CAP_EXIT'; did you mean 'HV_VMX_CAP_ENTRY'?
            error = vmx_set_ctlreg(HV_VMX_CAP_EXIT,
                                   ^~~~~~~~~~~~~~~
                                   HV_VMX_CAP_ENTRY
    In file included from src/vmm/intel/vmx.c:37:
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Hypervisor.framework/Headers/hv_vmx.h:62:2: note: 
          'HV_VMX_CAP_ENTRY' declared here
            HV_VMX_CAP_ENTRY
            ^
    1 error generated.
    make: *** [build/vmm/intel/vmx.o] Error 1

**Comment by xez** [comment]
I guess you have to update your OS X. These #defines only seem to be available in 10.10.3+

https://developer.apple.com/library/mac/releasenotes/General/APIDiffsMacOSX10_10_3/modules/Hypervisor.html

**Comment by rjp** [comment]
Ah. I would but that apparently hasn't made it to the work update server yet. Thanks!
