### ISSUE TITLE
Help text (-h) for memory size (-m) is incorrect.

### ISSUE THREAD

**Issue by rickard-von-essen** [mist64/xhyve#52]
The [help text](https://github.com/mist64/xhyve/blob/master/src/xhyve.c#L138) specifies **-m** as:
> -m: memory size in MB

But [xhyverun.sh](https://github.com/mist64/xhyve/blob/master/xhyverun.sh#L13) indicates that it can also be suffixed with (at least) **G** for gigabyte.

> MEM="-m 1G"

**Comment by jbergstroem** [comment]
It's using `expand_number` for parsing the input -- see: https://github.com/mist64/xhyve/blob/master/src/xhyve.c#L639 (which is most likely copied from the [counterpart in freebsd](https://github.com/freebsd/freebsd/blob/e79c62ff68fc74d88cb6f479859f6fae9baa5101/lib/libutil/expand_number.c#L39)).

A more appropriate text would probably be closer to what [bhyve has](https://www.freebsd.org/cgi/man.cgi?query=bhyve&apropos=0&sektion=8&manpath=FreeBSD+11-current&arch=default&format=html). Care to open a PR?

**Comment by rickard-von-essen** [comment]
Check, I can do that within a week or so.

**Comment by rickard-von-essen** [comment]
Just made a simple fix for this.

What about I start writing a man page (rewriting bhyve's) and open another PR for it?

**Comment by AntonioMeireles** [comment]
:+1::+1::+1: :smiley:

**Comment by rickard-von-essen** [comment]
See #55 for a manpage.

**Comment by rickard-von-essen** [comment]
I noted that the ```-b``` flag is missing from the detailed help text, but maybe it is not doing anything in xhyve.
