### ISSUE TITLE
Does xhyve have a headless mode?

### ISSUE THREAD

**Issue by c4milo** [mist64/xhyve#56]

**Comment by jbergstroem** [comment]
Thinking that you probably don't want to add the serial device and push stdout to it?

**Comment by c4milo** [comment]
Sure, why not. I actually tried what people have been doing in bhyve to achieve the same. This is changing:
```
LPC_DEV="-l com1,stdio"
```
to:
```
LPC_DEV="-l com1"
````

But xhyve stops booting the image when I do that.

**Comment by ailispaw** [comment]
I saw the following in https://github.com/nlf/dhyve.
```
nohup xhyve $args,"$cmdline" </dev/null >/dev/null 2>&1 &
```
It might work for you.

**Comment by rickard-von-essen** [comment]
Does xhyve have a head mode?

**Comment by xez** [comment]
If you don't want serial output (to stdio or another tty) just comment out the `LPC_DEV="-l com1,stdio"` line altogether, works fine.

**Comment by LaurentFough** [comment]
Good to know.

**Comment by c4milo** [comment]
It seems reasonable, thanks @ailispaw.
