### ISSUE TITLE
build error, use of undeclared identifier 'HV_VMX_CAP_EXIT'

### ISSUE THREAD

**Issue by Tombar** [mist64/xhyve#7]
Hello and congratulations for your great work! 

While trying to test xhyve i've got the following error, not sure if i'm missing something or what :(

```bash
tombar@Erebor:~/src/xhyve (master:7ffd07108710:)$ make
cc src/vmm/x86.c
cc src/vmm/vmm.c
cc src/vmm/vmm_host.c
cc src/vmm/vmm_mem.c
cc src/vmm/vmm_lapic.c
cc src/vmm/vmm_instruction_emul.c
cc src/vmm/vmm_ioport.c
cc src/vmm/vmm_callout.c
cc src/vmm/vmm_stat.c
cc src/vmm/vmm_util.c
cc src/vmm/vmm_api.c
cc src/vmm/intel/vmx.c
src/vmm/intel/vmx.c:507:25: error: use of undeclared identifier 'HV_VMX_CAP_EXIT'; did you mean 'HV_VMX_CAP_ENTRY'?
        error = vmx_set_ctlreg(HV_VMX_CAP_EXIT,
                               ^~~~~~~~~~~~~~~
                               HV_VMX_CAP_ENTRY
In file included from src/vmm/intel/vmx.c:37:
/System/Library/Frameworks/Hypervisor.framework/Headers/hv_vmx.h:62:2: note: 'HV_VMX_CAP_ENTRY' declared here
        HV_VMX_CAP_ENTRY
        ^
1 error generated.
make: *** [build/vmm/intel/vmx.o] Error 1
```

My specs if they help: 

OSX Yosemite 10.10.3
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro10,2
  Processor Name:	Intel Core i5
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB

Hope this helps and let me know if you want me to test something else.

Keep the good work! 

M

**Comment by xez** [comment]
Probably the same issue as https://github.com/mist64/xhyve/issues/4

**Comment by lemon-tree** [comment]
The solution to #4 was to update to 10.10.3, but that isn't quite the full story: you also need to ensure you have installed the most recent Xcode update to get the new libraries etc. Testing with just 10.10.3 but no updates to Xcode yields the same error.

**Comment by Tombar** [comment]
Indeed, in my case, just an update to osx command line tools solve the issue and I was able to compile it.

Thanks!
