### ISSUE TITLE
Initramfs unpacking failed: junk in compressed archive

### ISSUE THREAD

**Issue by cleesmith** [mist64/xhyve#74]
Following this article:
https://techblog.lankes.org/2015/05/01/My-Memo-to-build-a-custom-Linux-Kernel-for-Qemu/
then this one:
https://techblog.lankes.org/2015/07/05/Lightweight-Virtualization-on-OS-X/

I get a linux kernel 4.3.0 and initramfs which works using qemu:
```qemu-system-x86_64 -smp 2 -kernel ./bzImage -initrd ./myinitrd.cpio -append "root=/dev/ram0 rootfstype=ramfs init=init console=ttyS0" -nographic```

... but fails using xhyve:
```../build/xhyve -m 1G -c 2 -s 0:0,hostbridge -s 31,lpc -l com1,stdio -f kexec,bzImage,myinitrd.cpio,"earlyprintk=serial root=/dev/ram0 rootfstype=ramfs 
init=init console=ttyS0"```
...or:
```../build/xhyve -m 1G -c 2 -s 0:0,hostbridge -s 31,lpc -l com1,stdio -f kexec,bzImage,myinitrd.cpio,"earlyprintk=serial console=ttyS0"```

... with this message:
```
[    0.327131] Initramfs unpacking failed: junk in compressed archive
vm exit[0]
reason		VMX rip		0xffffffff81878ed0
inst_length	3
status		0
exit_reason	2
qualification	0x0000000000000000
inst_type		0
inst_error		0
./my_xhyverun.sh: line 27:  5078 Abort trap: 6
```
... same result when ```myinitrd.cpio``` is gzipped to ```myinitrd.cpio.gz```, probably doesn't matter.

OS X Yosemite 10.10.5
git clone https://github.com/mist64/xhyve.git
The included tiny core linux in the test folder works fine.
Any ideas as to why it's junk to one but not the other?
Did I miss something?
Thanks for this project.

**Comment by cleesmith** [comment]
It appears that 4.x kernels from https://www.kernel.org/ do not work with xhyve, odd, but pre-4 kernels work just fine. Thanks.

**Comment by luke-clifton** [comment]
I am seeing this issue, why was this closed? Is there a workaround?

**Comment by cleesmith** [comment]
There's no work around that I know of, and I never received a response to this issue so I closed it and moved on.

**Comment by xez** [comment]
Did you compile the kernel with CONFIG_KEXEC=y?

**Comment by peterwang** [comment]
I came across the same issue while installing NixOS. I solved it by adding an offset of 16777216 (16M) to ramdisk_start (in file src/firmware/kexec.c). btw: I got the 16M value by trial and error. Here is the patch for file kexec.c:

```
diff --git a/src/firmware/kexec.c b/src/firmware/kexec.c
index 61aeebb..b190289 100644
--- a/src/firmware/kexec.c
+++ b/src/firmware/kexec.c
@@ -186,6 +186,12 @@ kexec_load_ramdisk(char *path) {

        ramdisk_start = ALIGNUP((kernel.base + kernel.size), 0x1000ull);

+        /* temp hack */
+        char* tmpstr = getenv("RAMDISK_START");
+        if (tmpstr != NULL) {
+            ramdisk_start += ((uint32_t) atoi(tmpstr));
+        }
+
        if ((ramdisk_start + sz) > memory.size) {
                /* not enough memory */
                fclose(f);
```

**Comment by zchee** [comment]
@peterwang This problem has been fixed docker/hyperkit on 
https://github.com/docker/hyperkit/pull/66
https://github.com/docker/hyperkit/pull/66/files

**Comment by c4milo** [comment]
@zchee can it be back ported to xhyve?

**Comment by zchee** [comment]
@c4milo sure. I'll send a pull request.

**Comment by c4milo** [comment]
Nice, thanks!!
