### ISSUE TITLE
Windows Guest and GPU Passthrough?

### ISSUE THREAD

**Issue by jbddc** [mist64/xhyve#77]
Is there any hope for being able to have a windows guest with gpu passthrough for gaming? And if it is quite far-fetched, what can I do towards that end? Does it depend on bhyve development?

Thanks in advance for your time!

**Comment by taterbase** [comment]
As I understand it, Hypervisor.framework (what xhyve runs on top of) only exposes cpu interfaces utilizing [Intel VT](https://www-ssl.intel.com/content/www/us/en/virtualization/virtualization-technology/intel-virtualization-technology.html) so passthrough to the gpu would not be possible.
