### ISSUE TITLE
I have an older Macbook Pro (2008 model) that supports EPT/VT-x.

### ISSUE THREAD

**Issue by mikeatlas** [mist64/xhyve#85]
Hi there,

I have an older Macbook Pro circa 2008 with an [Intel Core 2 Duo T9600 @ 2.8GHz](http://ark.intel.com/products/35563/Intel-Core2-Duo-Processor-T9600-6M-Cache-2_80-GHz-1066-MHz-FSB). 

According to the Intel site, this cpu supports VT-x. Additionally, when I dual boot into Linux, `/proc/info` lists `vmx` as a flag. So --- I think I should be able to run xhyve, right? Your readme states Mac 2010+ ish.

**Comment by wtallis** [comment]
You've got VT-x support but your processor is too old to have EPT support.

**Comment by nlf** [comment]
@wtallis is correct, i don't believe it will work for you

**Comment by mikeatlas** [comment]
Thanks.
