### ISSUE TITLE
Conflict with HAXM

### ISSUE THREAD

**Issue by eapache** [mist64/xhyve#88]
Related to https://github.com/mist64/xhyve/issues/5 and https://www.virtualbox.org/ticket/14294 but (AFAICT) slightly different: if xhyve is already running, then starting HAXM fails in the same way that it does when virtualbox is already running.

cc @burke

**Comment by burke** [comment]
Related issue for HAXM has very recent activity: https://code.google.com/p/android/issues/detail?id=197915

**Comment by xez** [comment]
Unfortunately not something that is fixable from xhyve's side. :(
