### ISSUE TITLE
Is anyone still here?

### ISSUE THREAD

**Issue by carriercomm** [mist64/xhyve#95]
Just trying to find out if anything is currently being worked on?

I thought about trying to work through a bug here and there but need to know if it's worth it...

Thanks

**Comment by brodybits** [comment]
On Mar 24, 2016 7:12 PM, "Kevin Hatfield" <notifications@github.com> wrote:
>
> Just trying to find out if anything is currently being worked on?

I hope so!

There are multiple xhyve adapters for Docket on OSX.

**Comment by slarew** [comment]
I think active development may have moved to https://github.com/xhyve-xyz/xhyve

**Comment by jbergstroem** [comment]
@carriercomm in the land of open source its usually simpler just asking instead of asking about asking. Suggesting you file the issue as descriptive as possible (steps to repeat, etc).

**Comment by carriercomm** [comment]
Ok.... Right. So my "issue" is whether anyone is watching this. Really? Did you even read the question? Geez

**Comment by jbergstroem** [comment]
@carriercomm I'm a contributor, just like you. Just suggested that you jump into the issues or file an issue/pr if there was a specific bug you referred to.

**Comment by carriercomm** [comment]
The concern is that there have been a half dozen problems and not a response from the developer/s. I don't want to waste time working through a problem to have it patched with whatever is saved on their desktop. I get how open source works - which is why I took a mild offense. I am just like every other contributor - I don't have time to waste. I can fix a couple of things here but I just as well run any other 'dockerish' clone instead of wasting my time if it's going to patched in a later version (with something already completed). 

I am simply asking that whoever is going to work through the issues respond. If not then I consider it abandoned for now and I move on to something more useful.

Anyway, thanks again!
